# Generated by Django 6.0.4 on 2026-05-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_descricao_longa_alter_variacao_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produto',
        ),
    ]
